version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    ports:
       - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  payments-api:
    image: bs/expense-api:1.0-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${HOST_IP}/postgres