endpoints:
  health:
    path: /ping

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: password
    hikari:
      idle-timeout: 10000
  jpa:
    generate-ddl: true